"""empty message

Revision ID: 1aa3cab90158
Revises: 90ae256fd5e9
Create Date: 2019-08-10 16:23:48.557191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa3cab90158'
down_revision = '90ae256fd5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('has_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'has_id')
    # ### end Alembic commands ###
