"""empty message

Revision ID: 8d8e081922c8
Revises: e4d1e0d6047d
Create Date: 2019-08-17 16:25:16.885341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8e081922c8'
down_revision = 'e4d1e0d6047d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('asktime', sa.DateTime(), nullable=True),
    sa.Column('course_name', sa.String(length=32), nullable=True),
    sa.Column('teacher_name', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ask')
    # ### end Alembic commands ###
