"""empty message

Revision ID: e4d1e0d6047d
Revises: 1aa3cab90158
Create Date: 2019-08-16 23:06:09.574691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d1e0d6047d'
down_revision = '1aa3cab90158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stu_tea',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('course', sa.Column('updatetime', sa.DateTime(), nullable=True))
    op.add_column('teacher', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'description')
    op.drop_column('course', 'updatetime')
    op.drop_table('stu_tea')
    # ### end Alembic commands ###
